apiVersion: v1
kind: Config
preferences: {}
config_variables_file_path: .env

clusters:
- cluster:
    certificate-authority-data: ${LKE_CERT_AUTHORITY_DATA}
    server: https://cc04eddd-6458-4fd8-a1d8-0771c09a5363.eu-central-2.linodelke.net:443
  name: ${LKE_name}

users:
- name: lke93517-admin
  user:
    as-user-extra: {}
    token: ${LKE_token}

contexts:
- context:
    cluster: lke93517
    namespace: default
    user: ${LKE_CONTEXT_USER}
  name: ${LKE_CONTEXT_NAME}

current-context: ${LKE_CONTEXT_NAME}