name: publish
on: [push]
jobs:
publish-k8s_go_api_web-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.PROJECT_SECRET }}
- name: Build the k8s_go_api_web Docker image
run: |
       docker build . --tag ghcr.io/Kay-Wilkinson/k8s_go_api_web:latest
       docker run ghcr.io/Kay-Wilkinson/k8s_go_api_web:latest
       docker push ghcr.io/Kay-Wilkinson/k8s_go_api_web:latest